# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ML_TFLITE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'TensorFlowLiteSwift'

  # Pods for ML_TFLITE

  target 'ML_TFLITETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ML_TFLITEUITests' do
    # Pods for testing

  end

end
